### ISSUE TITLE
dataset issue

### ISSUE THREAD

**Issue by huliangxiao** [CRISTAL-3DSAM/InterFormer#1]
Your work looks amazing!
Can you provide the DuetDance Dataset download link?
Thanks a lot!

**Comment by bch544** [comment]
Unfortunately, to our knowledge, the dataset is not available online.
You will have to contact the authors of the dataset to get acces:

J. N. Kundu, H. Buckchash, P. Mandikal, R. M. V, A. Jamkhandi and R. V. Babu, "Cross-Conditioned Recurrent Networks for Long-Term Synthesis of Inter-Person Human Motion Interactions," 2020 IEEE Winter Conference on Applications of Computer Vision (WACV), Snowmass, CO, USA, 2020, pp. 2713-2722, doi: 10.1109/WACV45572.2020.9093627.

**Comment by huliangxiao** [comment]
Thanks!
