### ISSUE TITLE
About obtaining skeletons_A.mat and skeletons_B.mat in SBU

### ISSUE THREAD

**Issue by AlbertTan404** [CRISTAL-3DSAM/InterFormer#2]
Great work! I wonder how did you distinguish the _actor_ and _reactor_ thus obtain skeletons_A.mat and skeletons_B.mat in SBU. It seems that there is no code to generate the matrices. I loaded the official data but found that there are only lines of 90-dimension data (which supposed to be 2 human * 15 joints * 3-d pos), but no indicator for _actor_ and _reactor_ is found.

**Comment by bch544** [comment]
For SBU, since the dataset was small, we annotated the data manually. this is why we provided the preprocessed data with the code.

**Comment by AlbertTan404** [comment]
> For SBU, since the dataset was small, we annotated the data manually. this is why we provided the preprocessed data with the code.

Got it, thanks for your response.
